var map_cfg = {
  mapWidth: "100%",
  mapHeight: 500,
  shadowWidth: 2,
  shadowOpacity: 0.2,
  shadowColor: "black",
  shadowX: 0,
  shadowY: 0,
  iPhoneLink: true,
  isNewWindow: true,
  zoomEnable: false,
  zoomEnableControls: false,
  zoomIgnoreMouseScroll: false,
  zoomMax: 8,
  zoomStep: 0.8,
  borderColor: "#ffffff",
  borderColorOver: "#ffffff",
  borderOpacity: 0.5,
  nameColor: "#ffffff",
  nameColorOver: "#ffffff",
  nameFontSize: "10px",
  nameFontWeight: "bold",
  nameStroke: true,
  nameStrokeColor: "#000000",
  nameStrokeColorOver: "#000000",
  nameStrokeWidth: 1.5,
  nameStrokeOpacity: 0.5,
  overDelay: 300,
  nameAutoSize: false,
  tooltipOnHighlightIn: false,
  freezeTooltipOnClick: false,
  mapId: "7f5w8",
  map_data: {
    st1: {
      link: "",
      name: "Andaman and Nicobar Islands",
      color: "#e01fb6",
      comment: "",
      colorOver: "#a75252",
      shortname: "AN",
    },
    st2: {
      link: "",
      name: "Andhra Pradesh",
      color: "#d31fe0",
      comment: "",
      colorOver: "#a75252",
      shortname: "AP",
    },
    st3: {
      link: "",
      name: "Arunachal Pradesh",
      color: "#e01f32",
      comment: "",
      colorOver: "#a75252",
      shortname: "AR",
    },
    st4: {
      link: "",
      name: "Assam",
      color: "#22e01f",
      comment: "",
      colorOver: "#a75252",
      shortname: "AS",
    },
    st5: {
      link: "",
      name: "Bihar",
      color: "#9e78a1",
      comment: "",
      colorOver: "#a75252",
      shortname: "BR",
    },
    st6: {
      link: "",
      name: "Chandigarh",
      color: "#7798bb",
      comment: "",
      colorOver: "#366CA3",
      shortname: "CH",
    },
    st7: {
      link: "",
      name: "Chhattisgarh",
      color: "#0d48bf",
      comment: "",
      colorOver: "#a75252",
      shortname: "CT",
    },
    st8: {
      link: "",
      name: "Dadra and Nagar Haveli and Daman and Diu",
      color: "#7798bb",
      comment: "",
      colorOver: "#366CA3",
      shortname: "DD",
    },
    st9: {
      link: "",
      name: "National Capital Territory of Delhi",
      color: "#7798bb",
      comment: "",
      colorOver: "#366CA3",
      shortname: "DL",
    },
    st10: {
      link: "",
      name: "Goa",
      color: "#e0991f",
      comment: "",
      colorOver: "#a75252",
      shortname: "GA",
    },
    st11: {
      link: "",
      name: "Gujarat",
      color: "#e0991f",
      comment: "",
      colorOver: "#a75252",
      shortname: "GJ",
    },
    st12: {
      link: "",
      name: "Himachal Pradesh",
      color: "#d22d2d",
      comment: "",
      colorOver: "#a75252",
      shortname: "HP",
    },
    st13: {
      link: "",
      name: "Haryana",
      color: "#d2cd2d",
      comment: "",
      colorOver: "#a75252",
      shortname: "HR",
    },
    st14: {
      link: "",
      name: "Jharkhand",
      color: "#3e654f",
      comment: "",
      colorOver: "#a75252",
      shortname: "JH",
    },
    st15: {
      link: "",
      name: "Jammu and Kashmir",
      color: "#2B78E4",
      comment: "",
      colorOver: "#a75252",
      shortname: "JK",
    },
    st16: {
      link: "",
      name: "Karnataka",
      color: "#e01f32",
      comment: "",
      colorOver: "#a75252",
      shortname: "KA",
    },
    st17: {
      link: "",
      name: "Kerala",
      color: "#e0da1f",
      comment: "",
      colorOver: "#a75252",
      shortname: "KL",
    },
    st18: {
      link: "",
      name: "Ladakh",
      color: "#d22da6",
      comment: "",
      colorOver: "#a75252",
      shortname: "LA",
    },
    st19: {
      link: "",
      name: "Lakshadweep",
      color: "#d31fe0",
      comment: "",
      colorOver: "#a75252",
      shortname: "LD",
    },
    st20: {
      link: "",
      name: "Maharashtra",
      color: "#e0da1f",
      comment: "",
      colorOver: "#a75252",
      shortname: "MH",
    },
    st21: {
      link: "",
      name: "Meghalaya",
      color: "#d31fe0",
      comment: "",
      colorOver: "#a75252",
      shortname: "ML",
    },
    st22: {
      link: "",
      name: "Manipur",
      color: "#e0da1f",
      comment: "",
      colorOver: "#a75252",
      shortname: "MN",
    },
    st23: {
      link: "state_page.html?name=mp",
      name: "Madhya Pradesh",
      color: "#78a19e",
      comment: "",
      colorOver: "#a75252",
      shortname: "MP",
    },
    st24: {
      link: "",
      name: "Mizoram",
      color: "#0d48bf",
      comment: "",
      colorOver: "#a75252",
      shortname: "MZ",
    },
    st25: {
      link: "",
      name: "Nagaland",
      color: "#e0991f",
      comment: "",
      colorOver: "#a75252",
      shortname: "NL",
    },
    st26: {
      link: "",
      name: "Orissa",
      color: "#bf0d63",
      comment: "",
      colorOver: "#a75252",
      shortname: "OR",
    },
    st27: {
      link: "",
      name: "Punjab",
      color: "#2dd2d0",
      comment: "",
      colorOver: "#a75252",
      shortname: "PB",
    },
    st28: {
      link: "",
      name: "Puducherry",
      color: "#e0991f",
      comment: "",
      colorOver: "#a75252",
      shortname: "PY",
    },
    st29: {
      link: "state_page.html?name=rajasthan",
      name: "Rajasthan",
      color: "#e01fb6",
      comment: "",
      colorOver: "#a75252",
      shortname: "RJ",
    },
    st30: {
      link: "",
      name: "Sikkim",
      color: "#bf0d63",
      comment: "",
      colorOver: "#a75252",
      shortname: "SK",
    },
    st31: {
      link: "",
      name: "Telangana",
      color: "#9e78a1",
      comment: "",
      colorOver: "#a75252",
      shortname: "TG",
    },
    st32: {
      link: "state_page.html?name=tamil",
      name: "Tamil Nadu",
      color: "#22e01f",
      comment: "",
      colorOver: "#a75252",
      shortname: "TN",
    },
    st33: {
      link: "",
      name: "Tripura",
      color: "#bf0d63",
      comment: "",
      colorOver: "#a75252",
      shortname: "TR",
    },
    st34: {
      link: "",
      name: "Uttar Pradesh",
      color: "#22e01f",
      comment: "",
      colorOver: "#a75252",
      shortname: "UP",
    },
    st35: {
      link: "",
      name: "Uttarakhand",
      color: "#221fe0",
      comment: "",
      colorOver: "#a75252",
      shortname: "UT",
    },
    st36: {
      link: "",
      name: "West Bengal",
      color: "#0d48bf",
      comment: "",
      colorOver: "#a75252",
      shortname: "WB",
    },
  },
  points: {},
};
